Fix colors and add colors to error messages

diff --git a/wdt b/wdt
--- a/wdt
+++ b/wdt
@@ -6,6 +6,7 @@
 # They are left mainly for informational purposes.
 
 # Colors
+RED='\033[0;31m'
 GREEN='\033[0;32m'
 CYAN='\033[0;35m'
 NC='\033[0m' # No Color
@@ -13,7 +14,7 @@ CC=$GREEN # Chosen Color
 
 # Error out
 die() {
-    printf '%s\n' "$1" >&2
+    printf '%b\n' "$1" >&2 # use %b instead of %s to enable colors
     exit 1
 }
 
@@ -64,42 +65,42 @@ while :; do
                 name=$2
                 shift
             else
-                die 'ERROR: "--name" requires a non-empty option argument.'
+                die "$RED ERROR:$NC \"--name\" requires a non-empty option argument."
             fi
             ;;
         --name=?*)
             name=${1#*=} # Delete everything up to "=" and assign the remainder.
             ;;
         --name=)         # Handle the case of an empty --name=
-            die 'ERROR: "--name" requires a non-empty option argument.'
+            die "$RED ERROR:$NC \"--name\" requires a non-empty option argument."
             ;;
         -p|--port)       # Takes an option argument; ensure it has been specified.
             if [ "$2" ]; then
                 port=$2
                 shift
             else
-                die 'ERROR: "--port" requires a non-empty option argument.'
+                die "$RED ERROR:$NC \"--port\" requires a non-empty option argument."
             fi
             ;;
         --port=?*)
             port=${1#*=} # Delete everything up to "=" and assign the remainder.
             ;;
         --port=)         # Handle the case of an empty --name=
-            die 'ERROR: "--port" requires a non-empty option argument.'
+            die "$RED ERROR:$NC \"--port\" requires a non-empty option argument."
             ;;
         -e|--email)       # Takes an option argument; ensure it has been specified.
             if [ "$2" ]; then
                 email=$2
                 shift
             else
-                die 'ERROR: "--email" requires a non-empty option argument.'
+                die "$RED ERROR:$NC \"--email\" requires a non-empty option argument."
             fi
             ;;
         --email=?*)
             email=${1#*=} # Delete everything up to "=" and assign the remainder.
             ;;
         --email=)         # Handle the case of an empty --name=
-            die 'ERROR: "--email" requires a non-empty option argument.'
+            die "$RED ERROR:$NC \"--email\" requires a non-empty option argument."
             ;;
         -s|--secure)
             enable_ssl=true
@@ -116,7 +117,7 @@ while :; do
             ;;
         -?*)
             # printf 'WARNING\: Unknown option (ignored): %s\n' "$1" >&2
-            echo -e "ERROR: Invalid option -- \"$1\". Try \"wdt --help\" for more information."
+            echo -e "$RED ERROR:$NC Invalid option -- \"$1\". Try \"wdt --help\" for more information."
             exit 1
             ;;
         *)               # Default case: No more options, so break out of the loop.
@@ -134,7 +135,7 @@ done
 if $delete_domain; then
 
     if [ ! "$name" ]; then
-        die 'ERROR: Please provide the DOMAIN to delete.'
+        die "$RED ERROR:$NC Please provide the DOMAIN to delete."
     fi
 
     read -p "Are you sure you want to delete $name? [y|n] " -n 1 -r
@@ -142,20 +143,20 @@ if $delete_domain; then
     if [[ $REPLY =~ ^[Yy]$ ]]; then
 
         if [ -f /etc/nginx/sites-available/$name ]; then
-            echo -n "Deleting /etc/nginx/sites-available/$name... "
+            echo -en "$CC[nginx]:$NC Deleting /etc/nginx/sites-available/$name... "
             sudo rm /etc/nginx/sites-available/$name
             echo "Done"
         else
-            die "ERROR: $name entry not found."
+            die "$RED ERROR:$NC $name entry not found."
         fi
         # -L check if there is a symlink, no matter broken or not
         if [ -L /etc/nginx/sites-enabled/$name ]; then
-            echo -n "Deleting the symlink /etc/nginx/sites-enabled/$name... "
+            echo -en "$CC[nginx]:$NC Deleting the symlink /etc/nginx/sites-enabled/$name... "
             sudo rm /etc/nginx/sites-enabled/$name
             echo "Done"
         fi
         if [ -d /var/www/$name ]; then
-            echo -n "Deleting /var/www/$name... "
+            echo -en "$CC[nginx]:$NC Deleting /var/www/$name... "
             sudo rm -r /var/www/$name
             echo "Done"
         fi
@@ -163,7 +164,7 @@ if $delete_domain; then
 
         # check if ssl certificate exists
         if [[ $(sudo certbot certificates 2> /dev/null) == *"$name"* ]]; then
-            echo -n "Deleting the SSL certificate for $name... "
+            echo -en "$CC[certbot]:$NC Deleting the SSL certificate for $name... "
             sudo certbot delete --cert-name $name &> /dev/null
             echo "Done"
         fi
@@ -174,7 +175,7 @@ if $delete_domain; then
         sed -i "/certbot renew --quiet/d" $tmpfile
         crontab -u $(logname) $tmpfile && rm -f $tmpfile
 
-        echo "The setup for $name was successfully deleted."
+        echo -e "$CYAN The setup for $name was successfully deleted.$NC"
         exit
     else
         exit 0
@@ -183,60 +184,60 @@ fi
 
 # if the necessary arguments are missing, error out
 if [ ! "$name" ] || [ ! "$port" ]; then
-    die 'ERROR: Please provide both the DOMAIN and the PORT. Try "wdt --help" for more information.'
+    die "$RED ERROR:$NC Please provide both the DOMAIN and the PORT. Try \"wdt --help\" for more information."
 elif $enable_ssl && [ ! "$email" ]; then
-    die 'ERROR: Please provide the EMAIL to connect to the certificate for registration and recovery contact.'
+    die "$RED ERROR:$NC Please provide the EMAIL to connect to the certificate for registration and recovery contact."
 fi
 
 # ---------------------------- Installing stuff ---------------------------
 # Install nodejs
 if [ ! -d ~/.n ]; then
-    echo -n "$CC[nodejs]:$NC Installing n version manager with node.js LTS... "
+    echo -en "$CC[nodejs]:$NC Installing n version manager with node.js LTS... "
     curl -sL https://git.io/n-install | N_PREFIX=~/.n bash -s -- -q -n
     # fix the ownership problem
     sudo chown -R $(logname):$(logname) /home/$(logname)/.n
     echo "Done"
 else
-    echo "$CC[nodejs]$NC: Node is already installed"
+    echo -e "$CC[nodejs]$NC: Node is already installed"
 fi
 
 # Install pm2
 if [ ! -f /home/$(logname)/.n/bin/pm2 ]; then
-    echo -n "$CC[pm2]:$NC Installing pm2, a process manager for node.js... "
+    echo -en "$CC[pm2]:$NC Installing pm2, a process manager for node.js... "
     # make sudo use $PATH instead of $SECURE_PATH, otherwise npm won't work
     sudop "npm install --global pm2 &> /dev/null"
     echo "Done"
 else
-    echo "$CC[pm2]:$NC PM2 process manager is already installed"
+    echo -e "$CC[pm2]:$NC PM2 process manager is already installed"
 fi
 
 # Install ufw
 if [ ! -f /usr/sbin/ufw ]; then
-    echo -n "$CC[ufw]:$NC Installing ufw -- the Uncomplicated Firewall... "
+    echo -en "$CC[ufw]:$NC Installing ufw -- the Uncomplicated Firewall... "
     sudo apt install ufw -y > /dev/null
     echo "Done"
 else
-    echo "$CC[ufw]:$NC Uncomplicated Firewall is already installed"
+    echo -e "$CC[ufw]:$NC Uncomplicated Firewall is already installed"
 fi
 
 # Install nginx
 if [ ! -f /usr/sbin/nginx ]; then
-    echo -n "$CC[nginx]:$NC Installing nginx... "
+    echo -en "$CC[nginx]:$NC Installing nginx... "
     sudo apt install nginx -y > /dev/null
     echo "Done"
 else
-    echo "$CC[nginx]:$NC Nginx is already installed"
+    echo -e "$CC[nginx]:$NC Nginx is already installed"
 fi
 
 # ---------------------------- Actual commands ----------------------------
 # npm install part
 if [ ! -f ./package.json ]; then
-    echo -n "$CC[npm]:$NC Initializing npm and installing Express.js... "
+    echo -en "$CC[npm]:$NC Initializing npm and installing Express.js... "
     sudop "npm init -y > /dev/null"
     sudop "npm install express &> /dev/null"
     echo "Done"
 elif [ ! -d ./node_modules/express ]; then
-    echo -n "$CC[npm]:$NC Installing Express.js... "
+    echo -en "$CC[npm]:$NC Installing Express.js... "
     sudop "npm install express &> /dev/null"
     echo "Done"
 fi
@@ -250,14 +251,14 @@ elif [[ $(locale | grep LANG | cut -d= -f2 | cut -d_ -f1) == *"en"* ]]; then
 fi
 # make sure firewall is enabled and allows ssh, http and https
 if sudo ufw status | grep -qw $ufwstatus; then
-    echo -n "$CC[ufw]:$NC Enabling ufw and allowing ssh (22), http (80) and https (443)... "
+    echo -en "$CC[ufw]:$NC Enabling ufw and allowing ssh (22), http (80) and https (443)... "
     sudo ufw enable > /dev/null
     sudo ufw allow ssh > /dev/null
     sudo ufw allow http > /dev/null
     sudo ufw allow https > /dev/null
     echo "Done"
 else
-    echo -n "$CC[ufw]:$NC Firewall is enabled. Allowing ssh (22), http (80) and https (443)... "
+    echo -en "$CC[ufw]:$NC Firewall is enabled. Allowing ssh (22), http (80) and https (443)... "
     sudo ufw allow ssh > /dev/null
     sudo ufw allow http > /dev/null
     sudo ufw allow https > /dev/null
@@ -275,20 +276,20 @@ if [ ! -d /var/www/$name/html ]; then
 
     # create the directories for the site
     sudo mkdir -p /var/www/$name/html
-    echo "$CC[nginx]:$NC Creating a directory /var/www/$name/html... "
+    echo -e "$CC[nginx]:$NC Creating a directory /var/www/$name/html... "
     # assing the correct ownership
     # using $(logname) allows to force run this script with sudo and still get the username
     sudo chown -R $(logname):$(logname) /var/www/$name/html
     # make permissions of our web roots are correct
     sudo chmod -R 755 /var/www
     # creating sample page for the site
-    echo "$CC[nginx]:$NC Adding a sample index.html to /var/www/$name/html... "
+    echo -e "$CC[nginx]:$NC Adding a sample index.html to /var/www/$name/html... "
     index_html_data="<html>\n\t<head>\n\t\t<title> Welcome to $name! </title>\n\t</head>\n\t<body>\n\t\t<h1> Success! The $name server block is working! </h1>\n\t</body>\n</html>"
     echo -e $index_html_data > /var/www/$name/html/index.html
     ####### optional end #######
 
     # creating Server Block Files for Each Domain
-    echo "$CC[nginx]:$NC Creating /etc/nginx/sites-available/$name and adding the configuration to redirect to port $port... "
+    echo -e "$CC[nginx]:$NC Creating /etc/nginx/sites-available/$name and adding the configuration to redirect to port $port... "
     nginx_sites_available_file_data="# Virtual Host configuration for $name\n#\nserver {\n\tlisten 80;\n\tlisten [::]:80;\n\n\tserver_name $name www.$name;\n\n\troot /var/www/$name/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\n\tlocation / {\n\t\tproxy_pass http://localhost:$port; # whatever port your app runs on\n\t\tproxy_http_version 1.1;\n\t\tproxy_set_header Upgrade \$http_upgrade;\n\t\tproxy_set_header Connection 'upgrade';\n\t\tproxy_set_header Host \$host;\n\t\tproxy_cache_bypass \$http_upgrade;\n\t}\n}"
     # create new server file and correct it's permissions and ownership
     echo -e $nginx_sites_available_file_data > $name
@@ -296,12 +297,12 @@ if [ ! -d /var/www/$name/html ]; then
     sudo chown -R root:root /etc/nginx/sites-available/$name
     sudo chmod 644 /etc/nginx/sites-available/$name
     # create a symlink to sites-enabled
-    echo "$CC[nginx]:$NC Adding a symlink from /etc/nginx/sites-enabled/$name to /etc/nginx/sites-available/$name... "
+    echo -e "$CC[nginx]:$NC Adding a symlink from /etc/nginx/sites-enabled/$name to /etc/nginx/sites-available/$name... "
     sudo ln -s /etc/nginx/sites-available/$name /etc/nginx/sites-enabled/
     # uncomment one line in order to avoid a possible hash bucket memory problem that can arise from adding additional server names
     sudo sed -i "s|# server_names_hash_bucket_size 64;|server_names_hash_bucket_size 64;|g" /etc/nginx/nginx.conf
     # restart nginx
-    echo -n "$CC[nginx]:$NC Restarting nginx... "
+    echo -en "$CC[nginx]:$NC Restarting nginx... "
     sudo systemctl restart nginx
     echo "Done"
 fi
@@ -311,26 +312,26 @@ if $enable_ssl; then
 
     # Install certbot with nginx extension
     if [ ! -f /usr/bin/certbot ]; then
-        echo -n "$CC[certbot]:$NC Installing Certbot from Let's Encrypt with the nginx plugin... "
+        echo -en "$CC[certbot]:$NC Installing Certbot from Let's Encrypt with the nginx plugin... "
         sudo apt install python3-certbot-nginx -y > /dev/null
         echo "Done"
     elif [ ! -d /usr/lib/python3/dist-packages/certbot_nginx ]; then
-        echo -n "$CC[certbot]:$NC Installing the nginx plugin for certbot... "
+        echo -en "$CC[certbot]:$NC Installing the nginx plugin for certbot... "
         sudo apt install python3-certbot-nginx -y > /dev/null
         echo "Done"
     else
-        echo "$CC[certbot]:$NC Certbot with nginx plugin is already installed"
+        echo -e "$CC[certbot]:$NC Certbot with nginx plugin is already installed"
     fi
 
     # Enable SSL
-    echo -n "$CC[certbot]:$NC Installing the certificate for $name... "
+    echo -en "$CC[certbot]:$NC Installing the certificate for $name... "
     sudo certbot --nginx -d $name -d www.$name --email $email --agree-tos --no-eff-email --redirect &> /dev/null
     echo "Done"
 fi
 
 # Crontab part
 if $autorenew_ssl; then
-    echo -n "$CC[crontab]:$NC Creating a cron job for certbot to renew the certificate... "
+    echo -en "$CC[crontab]:$NC Creating a cron job for certbot to renew the certificate... "
     # create a tempfile
     tmpfile=$(userdo mktemp)
     # write out current crontab
@@ -342,4 +343,4 @@ if $autorenew_ssl; then
     echo "Done"
 fi
 
-echo "$CYAN The setup for $name is complete. Use \"pm2 start app.js\" to start your app.$NC"
+echo -e "$CYAN The setup for $name is complete. Use \"pm2 start app.js\" to start your app.$NC"
